trigger:
- master

pr:
- '*'

pool:
  name : 'Agent'

variables:
  dockerImageName: 'my-httpd-image'

steps:
- checkout: self


- task: Docker@2
  inputs:
    containerRegistry: 'SurajDemoConnection'
    repository: 'surajsp9/repo1'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'