trigger:
- master

pr:
- '*'

pool:
  name : 'Default'

variables:
  dockerImageName: 'my-httpd-image'

steps:
- checkout: self

- task: Docker@2
  inputs:
    containerRegistry: 'DockerHubConnection' # Replace with your Docker registry connection name if necessary
    repository: 'your-docker-username/$(dockerImageName)'
    command: 'build'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)
